### ISSUE TITLE
source code for the node

### ISSUE THREAD

**Issue by animesh** [Nesvilab/PD-Nodes#12]
I am wondering if the source code is available for the node? I would like to try to add the PTMshepherd to the same, if possible?

**Comment by huiyinc** [comment]
Hi~

I am sorry but the source code is currently unavailable.
Also, I think implementing PTMshepherd as a node in PD is different from
the implementation of MSFragger to PD.For example, the input files are
different. MSFragger accepts raw/mzML files as the input, but PTMshepherd
requires PSM tables generated by Philosopher (as I remember). Another thing
to be considered is: what the node type should PTMshepherd be implemented,
processing or consensus node? Different node types provide different levels
of data information. There are more details need to be considered which
might take time to add PTMshepherd to PD. So, I would suggest to use
FragPipe if you want to run PTMshepherd.

Thanks.

Huiyin

Ani <notifications@github.com> 於 2020年8月20日 下午6:30 寫道：

﻿

I am wondering if the source code is available for the node? I would like
to try to add the PTMshepherd to the same, if possible?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nesvilab/PD-Nodes/issues/12>, or unsubscribe
